### ISSUE TITLE
Massive increase of file size while using JIT

### ISSUE THREAD

**Issue by jaulz** [jjranalli/nightwind#14]
First of all, thanks for this great library! 😊  Though, what I noticed is that my CSS file grows by 400%. It's maybe worth noting that I use JIT mode. Is there any chance to keep the small size?

Before:
![image](https://user-images.githubusercontent.com/5358638/116404299-cb6fdd00-a82e-11eb-9b79-b61fa6ef0dbe.png)

After:
![image](https://user-images.githubusercontent.com/5358638/116404588-138eff80-a82f-11eb-95b9-5e8f69ae5994.png)

**Comment by jjranalli** [comment]
Thanks for opening the issue and for the kind words! :)

Indeed there are some issues related to JIT (see also #7 and the [open issue on tailwindcss repo](https://github.com/tailwindlabs/tailwindcss/issues/3972)), and I'm quite sure this issue is also related. If this is the case, it should get fixed once I'm able to release a JIT-compatible version of Nightwind (hopefully soon).

I'll be looking into this, but in the meantime could you please confirm me that app.css size doesn't grow unreasonably when JIT is disabled?

**Comment by jaulz** [comment]
Ah, I saw that issue but was not sure if that's related. I just did the comparison without JIT and it understandably grows as well but there it's not even half of it.

Without nightwind:
![image](https://user-images.githubusercontent.com/5358638/116417968-04627e80-a83c-11eb-8607-d92fffdc1504.png)

With nightwind:
![image](https://user-images.githubusercontent.com/5358638/116418260-425fa280-a83c-11eb-9c52-f13fbf867e9f.png)

**Comment by jjranalli** [comment]
Is this in production? It might be worth also checking out your purge settings in tailwind.config, as the css file size seems to be very large in both cases. 

As a comparison, the largest css file I made using Nightwind is of this [demo website](https://night-tailwindcss.vercel.app/) I made and it's ~30kb.

Nonetheless, I think it's probable that the 400% increase in file size was being caused by JIT. Will look into this!

**Comment by jaulz** [comment]
Sorry, that was the development build. In production it's like this:

Without nightwind:
![image](https://user-images.githubusercontent.com/5358638/116443742-4ac3d780-a854-11eb-90f6-96b0e654daa4.png)

With nightwind:
![image](https://user-images.githubusercontent.com/5358638/116443600-2667fb00-a854-11eb-8f4f-adc2d4d87491.png)

I have some non tailwind stuff there as well but here again it's more than twice the file size. Very strange...

**Comment by jjranalli** [comment]
Thank you for providing this. Would you mind also sharing your settings in tailwind.config.js? It would be great if you could also provide me with a repo to reproduce the specific issue.

**Comment by jjranalli** [comment]
Confirming that the increase in CSS file size is indeed related to JIT, as Nightwind is adding a lot of unneeded (and wrong) rules to the css. This issue should be solved with the next release of Nightwind with full JIT support, which I hope to release soon since I finally managed to understand the underlying issue.

As to the increase in CSS file size when JIT is disabled, this depends on how many color classes you're using in your app (the more classes, the more Nightwind has to generate) and especially if you have typography enabled in Nightwind's config (I may be able to optimise this in the future). If you think the anomalous increase is not related to any of these, please provide a reproduction repo so I can look into it. Thanks!

**Comment by jaulz** [comment]
@jjranalli oh, thanks for that extensive response and sorry that I missed your question before! 😊 I think I will just try your next release and let you know in case I experience further issues.
