### ISSUE TITLE
Does not work with important selector configured

### ISSUE THREAD

**Issue by bep** [jjranalli/nightwind#9]
I had a head-scratching moment getting this promising plugin to work. Then I commented out the `important` config option (see below), and it all started to work.

```
module.exports = {
	darkMode: 'class', 
	important: '#myapp',
```

```
├── nightwind@1.1.7
```

This is a great tool, btw, much appreciated. I started added dark classes to a site by hand, and got dizzy pretty fast.

**Comment by jjranalli** [comment]
Thanks for opening this! I was able to reproduce it, I'll fix it in the next release (probably tomorrow).

Really glad you're enjoying Nightwind by the way! :)

**Comment by jjranalli** [comment]
Closing this as the 1.1.8 release should fix the issue. I've also implemented a new 'importantNode' config option to enable the important ID selector on the same element that contains the 'nightwind' and the toggled 'dark' classes, instead of a parent element. You can find the details in in the [new related readme section](https://github.com/jjranalli/nightwind#important-selector)

Feel free to reopen the issue if you find any bug around this implementation!
